name: Deploy ACI

on:
  workflow_call:
    inputs:
      NAME:
        required: true
        type: string
      CONTAINER_NAME:
        required: true
        type: string
      START_COMMAND:
        required: true
        type: string
      STAGE:
        required: true
        type: string
      TAG:
        required: true
        type: string
      RESOURCE_GROUP:
        required: true
        type: string
      VNET:
        required: true
        type: string
      MEMORY:
        required: true
        type: string
      CPU:
        required: true
        type: string
      LOG_WORKSPACE_ID:
        required: true
        type: string
      LOG_WORKSPACE_KEY:
        required: true
        type: string
      AZURE_STORAGE_CONNECTION_STRING:
        required: true
        type: string
      AZURE_STORAGE_CONTAINER_SOURCE:
        required: true
        type: string
      ACTIVITIES_LAKE_CONTAINER_NAME:
        required: true
        type: string
      FILE_VALIDATION_URL:
        required: true
        type: string
      SCHEMA_VALIDATION_URL:
        required: true
        type: string
      FILE_VALIDATION_KEY_NAME:
        required: true
        type: string
      FILE_VALIDATION_KEY_VALUE:
        required: true
        type: string
      VALIDATOR_PARALLEL:
        required: true
        type: string
      FLATTENER_API_URL:
        required: true
        type: string
      FLATTENER_KEY_NAME:
        required: true
        type: string
      FLATTENER_KEY_VALUE:
        required: true
        type: string
      DB_HOST:
        required: true
        type: string
      DB_PORT:
        required: true
        type: string
      DB_USER:
        required: true
        type: string
      DB_PASS:
        required: true
        type: string
      DB_NAME:
        required: true
        type: string
      SOLR_API_URL:
        required: true
        type: string
      SOLR_USER:
        required: true
        type: string
      SOLR_PASSWORD:
        required: true
        type: string
      SOLR_500_SLEEP:
        required: true
        type: string
      SOLR_PARALLEL_PROCESSES:
        required: true
        type: string
      COMMSHUB_URL:
        required: true
        type: string
      COMMSHUB_KEY:
        required: true
        type: string

jobs:
  deploy-aci:
    name: Deploy to Azure Container Instances
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to Azure Container Instances"
        uses: "azure/CLI@1.0.4"
        with:
            azcliversion: 2.30.0
            inlineScript: |
              az container create \
              --resource-group "${{ inputs.RESOURCE_GROUP }}" \
              --image "${{ secrets.REGISTRY_LOGIN_SERVER }}/${{inputs.STAGE}}-${{inputs.NAME}}:${{ inputs.TAG }}" \
              --command-line "/usr/local/bin/python /code/handler.py -t ${{ inputs.START_COMMAND }}" \
              --registry-login-server "${{ secrets.REGISTRY_LOGIN_SERVER }}" \
              --registry-username "${{ secrets.REGISTRY_USERNAME }}" \
              --registry-password "${{ secrets.REGISTRY_PASSWORD }}" \
              --name "${{ inputs.STAGE }}-${{ inputs.NAME }}-${{ inputs.CONTAINER_NAME }}" \
              --location "uksouth" \
              --restart-policy "Always" \
              --ip-address "Private" \
              --vnet "${{ inputs.VNET }}" \
              --subnet "default" \
              --memory ${{ inputs.MEMORY }} \
              --cpu ${{ inputs.CPU }} \
              --os-type "Linux" \
              --log-analytics-workspace "${{ inputs.LOG_WORKSPACE_ID }}" \
              --log-analytics-workspace-key "${{ inputs.LOG_WORKSPACE_KEY }}" \
              --secure-environment-variables \
                AZURE_STORAGE_CONNECTION_STRING="${{ inputs.AZURE_STORAGE_CONNECTION_STRING }}" \
                AZURE_STORAGE_CONTAINER_SOURCE="${{ inputs.AZURE_STORAGE_CONTAINER_SOURCE }}" \
                ACTIVITIES_LAKE_CONTAINER_NAME="${{ inputs.ACTIVITIES_LAKE_CONTAINER_NAME }}" \
                VALIDATOR_API_URL="${{ inputs.FILE_VALIDATION_URL }}" \
                SCHEMA_VALIDATION_API_URL="${{ inputs.SCHEMA_VALIDATION_URL }}" \
                VALIDATOR_API_KEY_NAME="${{ inputs.FILE_VALIDATION_KEY_NAME }}" \
                VALIDATOR_API_KEY_VALUE="${{ inputs.FILE_VALIDATION_KEY_VALUE }}" \
                VALIDATOR_PARALLEL="${{ inputs.VALIDATOR_PARALLEL }}" \
                FLATTENER_API_URL="${{ inputs.FLATTENER_API_URL }}" \
                FLATTENER_KEY_NAME="${{ inputs.FLATTENER_KEY_NAME }}" \
                FLATTENER_KEY_VALUE="${{ inputs.FLATTENER_KEY_VALUE }}" \
                DB_HOST="${{ inputs.DB_HOST }}" \
                DB_PORT="${{ inputs.DB_PORT }}" \
                DB_USER="${{ inputs.DB_USER }}" \
                DB_PASS="${{ inputs.DB_PASS }}" \
                DB_NAME="${{ inputs.DB_NAME }}" \
                SOLR_API_URL="${{ inputs.SOLR_API_URL }}" \
                SOLR_USER="${{ inputs.SOLR_USER }}" \
                SOLR_PASSWORD="${{ inputs.SOLR_PASSWORD }}" \
                SOLR_500_SLEEP="${{ inputs.SOLR_500_SLEEP }}" \
                SOLR_PARALLEL_PROCESSES="${{ inputs.SOLR_PARALLEL_PROCESSES }}" \
                COMMSHUB_URL="${{ inputs.COMMSHUB_URL }}" \
                COMMSHUB_KEY="${{ inputs.COMMSHUB_KEY }}"
