name: Deploy_Refresher_To_Production_On_Release

on:
  release:
    types: [published]

env:
  STAGE: prod-aci-iati
  NAME: refresher
  VNET: prod-iati-refresher
  TAG: ${{ github.sha }}
  RESOURCE_GROUP: rg-refresher-prod
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.PROD_AZURE_STORAGE_CONNECTION_STRING }}
  AZURE_STORAGE_CONTAINER_SOURCE: ${{ secrets.PROD_AZURE_STORAGE_CONTAINER_SOURCE }}
  FILE_VALIDATION_URL: ${{ secrets.PROD_FILE_VALIDATION_URL }}
  FILE_VALIDATION_KEY_NAME: ${{ secrets.PROD_FILE_VALIDATION_KEY_NAME }}
  FILE_VALIDATION_KEY_VALUE: ${{ secrets.PROD_FILE_VALIDATION_KEY_VALUE }}
  SCHEMA_VALIDATION_URL: ${{ secrets.PROD_SCHEMA_VALIDATION_URL }}
  SCHEMA_VALIDATION_KEY_NAME: ${{ secrets.PROD_SCHEMA_VALIDATION_KEY_NAME }}
  SCHEMA_VALIDATION_KEY_VALUE: ${{ secrets.PROD_SCHEMA_VALIDATION_KEY_VALUE }}
  FLATTENER_API_URL: ${{ secrets.PROD_FLATTENER_API_URL }}
  FLATTENER_KEY_NAME: ${{ secrets.PROD_FLATTENER_KEY_NAME }}
  FLATTENER_KEY_VALUE: ${{ secrets.PROD_FLATTENER_API_KEY }}
  SOLR_API_URL: ${{ secrets.PROD_SOLR_API_URL }}
  SOLR_USER: ${{ secrets.PROD_SOLR_USER }}
  SOLR_PASSWORD: ${{ secrets.PROD_SOLR_PASSWORD }}
  SOLR_PARALLEL_PROCESSES: 2
  DB_USER: ${{ secrets.PROD_DB_USER }}
  DB_PASS: ${{ secrets.PROD_DB_PASS }}
  DB_HOST: ${{ secrets.PROD_DB_HOST }}
  DB_NAME: ${{ secrets.PROD_DB_NAME }}
  DB_PORT: ${{ secrets.PROD_DB_PORT }}
  LOG_WORKSPACE_ID: ${{ secrets.PROD_LOG_WORKSPACE_ID }}
  LOG_WORKSPACE_KEY: ${{ secrets.PROD_LOG_WORKSPACE_KEY }}
  ACTIVITIES_LAKE_CONTAINER_NAME: ${{ secrets.PROD_ACTIVITIES_LAKE_CONTAINER_NAME }}
  SOLR_500_SLEEP: ${{ secrets.PROD_SOLR_500_SLEEP }}
  COMMSHUB_URL: ${{ secrets.PROD_COMMSHUB_URL }}
  COMMSHUB_KEY: ${{ secrets.PROD_COMMSHUB_KEY }}
  REGISTRY_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  REGISTRY_USERNAME: ${{ secrets.ACR_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PROD_AZURE_CREDENTIALS }}
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: "Login to Azure Container Registry"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: "Build and push image"
        run: |
          docker build . -f Dockerfile -t ${{ env.REGISTRY_LOGIN_SERVER }}/$STAGE-$NAME:$TAG
          docker push ${{ env.REGISTRY_LOGIN_SERVER }}/$STAGE-$NAME:$TAG

      - name: "Delete existing containers"
        uses: "azure/CLI@1.0.4"
        with:
            azcliversion: 2.30.0
            inlineScript: |
              az container delete -y \
                --name "${{ env.STAGE }}-${{ env.NAME }}-refresh" \
                --resource-group "${{ env.RESOURCE_GROUP }}"
              az container delete -y \
                --name "${{ env.STAGE }}-${{ env.NAME }}-validate" \
                --resource-group "${{ env.RESOURCE_GROUP }}"
              az container delete -y \
                --name "${{ env.STAGE }}-${{ env.NAME }}-validate-activity-level" \
                --resource-group "${{ env.RESOURCE_GROUP }}"
              az container delete -y \
                --name "${{ env.STAGE }}-${{ env.NAME }}-flatten" \
                --resource-group "${{ env.RESOURCE_GROUP }}"
              az container delete -y \
                --name "${{ env.STAGE }}-${{ env.NAME }}-lakify" \
                --resource-group "${{ env.RESOURCE_GROUP }}"
              az container delete -y \
                --name "${{ env.STAGE }}-${{ env.NAME }}-solrize" \
                --resource-group "${{ env.RESOURCE_GROUP }}"
                
      - name: "Deploy Refresh to Azure Container Instances"
        uses: "azure/CLI@1.0.4"
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az container create \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --image "${{ env.REGISTRY_LOGIN_SERVER }}/${{env.STAGE}}-${{env.NAME}}:${{ env.TAG }}" \
            --command-line "/usr/local/bin/python /code/handler.py -t refreshloop" \
            --registry-login-server "${{ env.REGISTRY_LOGIN_SERVER }}" \
            --registry-username "${{ env.REGISTRY_USERNAME }}" \
            --registry-password "${{ env.REGISTRY_PASSWORD }}" \
            --name "${{ env.STAGE }}-${{ env.NAME }}-refresh" \
            --location "uksouth" \
            --restart-policy "Always" \
            --ip-address "Private" \
            --vnet "${{ env.VNET }}" \
            --subnet "default" \
            --memory "4" \
            --cpu "1" \
            --os-type "Linux" \
            --log-analytics-workspace "${{ env.LOG_WORKSPACE_ID }}" \
            --log-analytics-workspace-key "${{ env.LOG_WORKSPACE_KEY }}" \
            --secure-environment-variables \
              AZURE_STORAGE_CONNECTION_STRING="${{ env.AZURE_STORAGE_CONNECTION_STRING }}" \
              AZURE_STORAGE_CONTAINER_SOURCE="${{ env.AZURE_STORAGE_CONTAINER_SOURCE }}" \
              DB_HOST="${{ env.DB_HOST }}" \
              DB_PORT="${{ env.DB_PORT }}" \
              DB_USER="${{ env.DB_USER }}" \
              DB_PASS="${{ env.DB_PASS }}" \
              DB_NAME="${{ env.DB_NAME }}" \
              SOLR_API_URL="${{ env.SOLR_API_URL }}" \
              SOLR_USER="${{ env.SOLR_USER }}" \
              SOLR_PASSWORD="${{ env.SOLR_PASSWORD }}" \
              ACTIVITIES_LAKE_CONTAINER_NAME="${{ env.ACTIVITIES_LAKE_CONTAINER_NAME }}" \
              COMMSHUB_URL="${{ env.COMMSHUB_URL }}" \
              COMMSHUB_KEY="${{ env.COMMSHUB_KEY }}"

      - name: "Deploy Validate to Azure Container Instances"
        uses: "azure/CLI@1.0.4"
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az container create \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --image "${{ env.REGISTRY_LOGIN_SERVER }}/${{env.STAGE}}-${{env.NAME}}:${{ env.TAG }}" \
            --command-line "/usr/local/bin/python /code/handler.py -t validateloop" \
            --registry-login-server "${{ env.REGISTRY_LOGIN_SERVER }}" \
            --registry-username "${{ env.REGISTRY_USERNAME }}" \
            --registry-password "${{ env.REGISTRY_PASSWORD }}" \
            --name "${{ env.STAGE }}-${{ env.NAME }}-validate" \
            --location "uksouth" \
            --restart-policy "Always" \
            --ip-address "Private" \
            --vnet "${{ env.VNET }}" \
            --subnet "default" \
            --memory "2" \
            --cpu "1" \
            --os-type "Linux" \
            --log-analytics-workspace "${{ env.LOG_WORKSPACE_ID }}" \
            --log-analytics-workspace-key "${{ env.LOG_WORKSPACE_KEY }}" \
            --secure-environment-variables \
              AZURE_STORAGE_CONNECTION_STRING="${{ env.AZURE_STORAGE_CONNECTION_STRING }}" \
              AZURE_STORAGE_CONTAINER_SOURCE="${{ env.AZURE_STORAGE_CONTAINER_SOURCE }}" \
              VALIDATOR_API_URL="${{ env.FILE_VALIDATION_URL }}" \
              SCHEMA_VALIDATION_API_URL="${{ env.SCHEMA_VALIDATION_URL }}" \
              VALIDATOR_API_KEY_NAME="${{ env.FILE_VALIDATION_KEY_NAME }}" \
              VALIDATOR_API_KEY_VALUE="${{ env.FILE_VALIDATION_KEY_VALUE }}" \
              VALIDATOR_PARALLEL="${{ env.VALIDATOR_PARALLEL }}" \
              DB_HOST="${{ env.DB_HOST }}" \
              DB_PORT="${{ env.DB_PORT }}" \
              DB_USER="${{ env.DB_USER }}" \
              DB_PASS="${{ env.DB_PASS }}" \
              DB_NAME="${{ env.DB_NAME }}" \
              SOLR_API_URL="${{ env.SOLR_API_URL }}" \
              SOLR_USER="${{ env.SOLR_USER }}" \
              SOLR_PASSWORD="${{ env.SOLR_PASSWORD }}" \
              COMMSHUB_URL="${{ env.COMMSHUB_URL }}" \
              COMMSHUB_KEY="${{ env.COMMSHUB_KEY }}"

      - name: "Deploy Validate Activity Level to Azure Container Instances"
        uses: "azure/CLI@1.0.4"
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az container create \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --image "${{ env.REGISTRY_LOGIN_SERVER }}/${{env.STAGE}}-${{env.NAME}}:${{ env.TAG }}" \
            --command-line "/usr/local/bin/python /code/handler.py -t validate_activity_level_loop" \
            --registry-login-server "${{ env.REGISTRY_LOGIN_SERVER }}" \
            --registry-username "${{ env.REGISTRY_USERNAME }}" \
            --registry-password "${{ env.REGISTRY_PASSWORD }}" \
            --name "${{ env.STAGE }}-${{ env.NAME }}-validate-activity-level" \
            --location "uksouth" \
            --restart-policy "Always" \
            --ip-address "Private" \
            --vnet "${{ env.VNET }}" \
            --subnet "default" \
            --memory "4" \
            --cpu "1" \
            --os-type "Linux" \
            --log-analytics-workspace "${{ env.LOG_WORKSPACE_ID }}" \
            --log-analytics-workspace-key "${{ env.LOG_WORKSPACE_KEY }}" \
            --secure-environment-variables \
              AZURE_STORAGE_CONNECTION_STRING="${{ env.AZURE_STORAGE_CONNECTION_STRING }}" \
              AZURE_STORAGE_CONTAINER_SOURCE="${{ env.AZURE_STORAGE_CONTAINER_SOURCE }}" \
              VALIDATOR_API_URL="${{ env.ACTIVITY_VALIDATION_URL }}" \
              SCHEMA_VALIDATION_API_URL="${{ env.SCHEMA_VALIDATION_URL }}" \
              VALIDATOR_API_KEY_NAME="${{ env.FILE_VALIDATION_KEY_NAME }}" \
              VALIDATOR_API_KEY_VALUE="${{ env.FILE_VALIDATION_KEY_VALUE }}" \
              SCHEMA_VALIDATION_KEY_NAME="${{ env.SCHEMA_VALIDATION_KEY_NAME }}" \
              SCHEMA_VALIDATION_KEY_VALUE="${{ env.SCHEMA_VALIDATION_KEY_VALUE }}" \
              VALIDATOR_PARALLEL="${{ env.VALIDATOR_PARALLEL }}" \
              DB_HOST="${{ env.DB_HOST }}" \
              DB_PORT="${{ env.DB_PORT }}" \
              DB_USER="${{ env.DB_USER }}" \
              DB_PASS="${{ env.DB_PASS }}" \
              DB_NAME="${{ env.DB_NAME }}" \
              SOLR_API_URL="${{ env.SOLR_API_URL }}" \
              SOLR_USER="${{ env.SOLR_USER }}" \
              SOLR_PASSWORD="${{ env.SOLR_PASSWORD }}" \
              COMMSHUB_URL="${{ env.COMMSHUB_URL }}" \
              COMMSHUB_KEY="${{ env.COMMSHUB_KEY }}"

      - name: "Deploy Flatten to Azure Container Instances"
        uses: "azure/CLI@1.0.4"
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az container create \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --image "${{ env.REGISTRY_LOGIN_SERVER }}/${{env.STAGE}}-${{env.NAME}}:${{ env.TAG }}" \
            --command-line "/usr/local/bin/python /code/handler.py -t flattenloop" \
            --registry-login-server "${{ env.REGISTRY_LOGIN_SERVER }}" \
            --registry-username "${{ env.REGISTRY_USERNAME }}" \
            --registry-password "${{ env.REGISTRY_PASSWORD }}" \
            --name "${{ env.STAGE }}-${{ env.NAME }}-flatten" \
            --location "uksouth" \
            --restart-policy "Always" \
            --ip-address "Private" \
            --vnet "${{ env.VNET }}" \
            --subnet "default" \
            --memory "2" \
            --cpu "1" \
            --os-type "Linux" \
            --log-analytics-workspace "${{ env.LOG_WORKSPACE_ID }}" \
            --log-analytics-workspace-key "${{ env.LOG_WORKSPACE_KEY }}" \
            --secure-environment-variables \
              AZURE_STORAGE_CONNECTION_STRING="${{ env.AZURE_STORAGE_CONNECTION_STRING }}" \
              AZURE_STORAGE_CONTAINER_SOURCE="${{ env.AZURE_STORAGE_CONTAINER_SOURCE }}" \
              FLATTENER_API_URL="${{ env.FLATTENER_API_URL }}" \
              FLATTENER_KEY_NAME="${{ env.FLATTENER_KEY_NAME }}" \
              FLATTENER_KEY_VALUE="${{ env.FLATTENER_KEY_VALUE }}" \
              DB_HOST="${{ env.DB_HOST }}" \
              DB_PORT="${{ env.DB_PORT }}" \
              DB_USER="${{ env.DB_USER }}" \
              DB_PASS="${{ env.DB_PASS }}" \
              DB_NAME="${{ env.DB_NAME }}" \
              SOLR_API_URL="${{ env.SOLR_API_URL }}" \
              SOLR_USER="${{ env.SOLR_USER }}" \
              SOLR_PASSWORD="${{ env.SOLR_PASSWORD }}" \
              COMMSHUB_URL="${{ env.COMMSHUB_URL }}" \
              COMMSHUB_KEY="${{ env.COMMSHUB_KEY }}"

      - name: "Deploy Lakify to Azure Container Instances"
        uses: "azure/CLI@1.0.4"
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az container create \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --image "${{ env.REGISTRY_LOGIN_SERVER }}/${{env.STAGE}}-${{env.NAME}}:${{ env.TAG }}" \
            --command-line "/usr/local/bin/python /code/handler.py -t lakifyloop" \
            --registry-login-server "${{ env.REGISTRY_LOGIN_SERVER }}" \
            --registry-username "${{ env.REGISTRY_USERNAME }}" \
            --registry-password "${{ env.REGISTRY_PASSWORD }}" \
            --name "${{ env.STAGE }}-${{ env.NAME }}-lakify" \
            --location "uksouth" \
            --restart-policy "Always" \
            --ip-address "Private" \
            --vnet "${{ env.VNET }}" \
            --subnet "default" \
            --memory "2" \
            --cpu "1" \
            --os-type "Linux" \
            --log-analytics-workspace "${{ env.LOG_WORKSPACE_ID }}" \
            --log-analytics-workspace-key "${{ env.LOG_WORKSPACE_KEY }}" \
            --secure-environment-variables \
              AZURE_STORAGE_CONNECTION_STRING="${{ env.AZURE_STORAGE_CONNECTION_STRING }}" \
              AZURE_STORAGE_CONTAINER_SOURCE="${{ env.AZURE_STORAGE_CONTAINER_SOURCE }}" \
              ACTIVITIES_LAKE_CONTAINER_NAME="${{ env.ACTIVITIES_LAKE_CONTAINER_NAME }}" \
              SOLR_API_URL="${{ env.SOLR_API_URL }}" \
              DB_HOST="${{ env.DB_HOST }}" \
              DB_PORT="${{ env.DB_PORT }}" \
              DB_USER="${{ env.DB_USER }}" \
              DB_PASS="${{ env.DB_PASS }}" \
              DB_NAME="${{ env.DB_NAME }}" \
              COMMSHUB_URL="${{ env.COMMSHUB_URL }}" \
              COMMSHUB_KEY="${{ env.COMMSHUB_KEY }}"

      - name: "Deploy Solrize to Azure Container Instances"
        uses: "azure/CLI@1.0.4"
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az container create \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --image "${{ env.REGISTRY_LOGIN_SERVER }}/${{env.STAGE}}-${{env.NAME}}:${{ env.TAG }}" \
            --command-line "/usr/local/bin/python /code/handler.py -t solrizeloop" \
            --registry-login-server "${{ env.REGISTRY_LOGIN_SERVER }}" \
            --registry-username "${{ env.REGISTRY_USERNAME }}" \
            --registry-password "${{ env.REGISTRY_PASSWORD }}" \
            --name "${{ env.STAGE }}-${{ env.NAME }}-solrize" \
            --location "uksouth" \
            --restart-policy "Always" \
            --ip-address "Private" \
            --vnet "${{ env.VNET }}" \
            --subnet "default" \
            --memory "4" \
            --cpu "1" \
            --os-type "Linux" \
            --log-analytics-workspace "${{ env.LOG_WORKSPACE_ID }}" \
            --log-analytics-workspace-key "${{ env.LOG_WORKSPACE_KEY }}" \
            --secure-environment-variables \
              AZURE_STORAGE_CONNECTION_STRING="${{ env.AZURE_STORAGE_CONNECTION_STRING }}" \
              AZURE_STORAGE_CONTAINER_SOURCE="${{ env.AZURE_STORAGE_CONTAINER_SOURCE }}" \
              SOLR_API_URL="${{ env.SOLR_API_URL }}" \
              SOLR_USER="${{ env.SOLR_USER }}" \
              SOLR_PASSWORD="${{ env.SOLR_PASSWORD }}" \
              SOLR_PARALLEL_PROCESSES="${{ env.SOLR_PARALLEL_PROCESSES }}" \
              ACTIVITIES_LAKE_CONTAINER_NAME="${{ env.ACTIVITIES_LAKE_CONTAINER_NAME }}" \
              DB_HOST="${{ env.DB_HOST }}" \
              DB_PORT="${{ env.DB_PORT }}" \
              DB_USER="${{ env.DB_USER }}" \
              DB_PASS="${{ env.DB_PASS }}" \
              DB_NAME="${{ env.DB_NAME }}" \
              SOLR_500_SLEEP="${{ env.SOLR_500_SLEEP }}" \
              COMMSHUB_URL="${{ env.COMMSHUB_URL }}" \
              COMMSHUB_KEY="${{ env.COMMSHUB_KEY }}"

      
