name: Deploy_Refresher_To_Production_On_Push

on:
  release:
    types: [published]

env:
  STAGE: prod-aci-iati
  NAME: refresher
  TAG: ${{ github.sha }}
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.PROD_AZURE_STORAGE_CONNECTION_STRING }}
  AZURE_STORAGE_CONTAINER_SOURCE: ${{ secrets.PROD_AZURE_STORAGE_CONTAINER_SOURCE }}
  FILE_VALIDATION_URL: ${{ secrets.PROD_FILE_VALIDATION_URL }}
  FILE_VALIDATION_KEY_NAME: ${{ secrets.PROD_FILE_VALIDATION_KEY_NAME }}
  FILE_VALIDATION_KEY_VALUE: ${{ secrets.PROD_FILE_VALIDATION_KEY_VALUE }}
  FLATTENER_API_URL: ${{ secrets.FLATTENER_API_URL }}
  SOLR_API_URL: ${{ secrets.SOLR_API_URL }}
  SOLR_USER: ${{ secrets.SOLR_USER }}
  SOLR_PASSWORD: ${{ secrets.SOLR_PASSWORD }}
  VALIDATOR_PARALLEL: ${{ secrets.VALIDATOR_PARALLEL }}
  DB_USER: ${{ secrets.PROD_DB_USER }}
  DB_PASS: ${{ secrets.PROD_DB_PASS }}
  DB_HOST: ${{ secrets.PROD_DB_HOST }}
  DB_NAME: ${{ secrets.PROD_DB_NAME }}
  DB_PORT: ${{ secrets.PROD_DB_PORT }}
  LOG_WORKSPACE_ID: ${{ secrets.PROD_LOG_WORKSPACE_ID }}
  LOG_WORKSPACE_KEY: ${{ secrets.PROD_LOG_WORKSPACE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -f refresh-dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$STAGE-$NAME-refresh:$TAG
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$STAGE-$NAME-refresh:$TAG
          docker build . -f validate-dockerfile  -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$STAGE-$NAME-validate:$TAG
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$STAGE-$NAME-validate:$TAG
      - name: "Deploy Refresh to Azure Container Instances"
        uses: "azure/CLI@v1"
        with:
            azcliversion: 2.19.1
            inlineScript: |
              az container create \
              --resource-group "${{ secrets.RESOURCE_GROUP }}" \
              --image "${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.STAGE}}-${{env.NAME}}-refresh:${{ env.TAG }}" \
              --registry-login-server "${{ secrets.REGISTRY_LOGIN_SERVER }}" \
              --registry-username "${{ secrets.REGISTRY_USERNAME }}" \
              --registry-password "${{ secrets.REGISTRY_PASSWORD }}" \
              --name "${{ env.STAGE }}-${{ env.NAME }}-refresh" \
              --location "uksouth" \
              --restart-policy "Always" \
              --ip-address "Private" \
              --vnet "dev-iati-refresher" \
              --subnet "default" \
              --memory "4" \
              --cpu "1" \
              --os-type "Linux" \
              --log-analytics-workspace "${{ env.LOG_WORKSPACE_ID }}" \
              --log-analytics-workspace-key "${{ env.LOG_WORKSPACE_KEY }}" \
              --secure-environment-variables \
                AZURE_STORAGE_CONNECTION_STRING="${{ env.AZURE_STORAGE_CONNECTION_STRING }}" \
                AZURE_STORAGE_CONTAINER_SOURCE="${{ env.AZURE_STORAGE_CONTAINER_SOURCE }}" \
                SOLR_API_URL="${{ env.SOLR_API_URL }}" \
                SOLR_USER="${{ env.SOLR_USER }}" \
                SOLR_PASSWORD="${{ env.SOLR_PASSWORD }}" \
                DB_HOST="${{ env.DB_HOST }}" \
                DB_PORT="${{ env.DB_PORT }}" \
                DB_USER="${{ env.DB_USER }}" \
                DB_PASS="${{ env.DB_PASS }}" \
                DB_NAME="${{ env.DB_NAME }}"

      - name: "Deploy Validate to Azure Container Instances"
        uses: "azure/CLI@v1"
        with:
            azcliversion: 2.19.1
            inlineScript: |
              az container create \
              --resource-group "${{ secrets.RESOURCE_GROUP }}" \
              --image "${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.STAGE}}-${{env.NAME}}-validate:${{ env.TAG }}" \
              --registry-login-server "${{ secrets.REGISTRY_LOGIN_SERVER }}" \
              --registry-username "${{ secrets.REGISTRY_USERNAME }}" \
              --registry-password "${{ secrets.REGISTRY_PASSWORD }}" \
              --name "${{ env.STAGE }}-${{ env.NAME }}-validate" \
              --location "uksouth" \
              --restart-policy "Always" \
              --ip-address "Private" \
              --vnet "dev-iati-refresher" \
              --subnet "default" \
              --memory "2" \
              --cpu "1" \
              --os-type "Linux" \
              --log-analytics-workspace "${{ env.LOG_WORKSPACE_ID }}" \
              --log-analytics-workspace-key "${{ env.LOG_WORKSPACE_KEY }}" \
              --secure-environment-variables \
                AZURE_STORAGE_CONNECTION_STRING="${{ env.AZURE_STORAGE_CONNECTION_STRING }}" \
                AZURE_STORAGE_CONTAINER_SOURCE="${{ env.AZURE_STORAGE_CONTAINER_SOURCE }}" \
                VALIDATOR_API_URL="${{ env.FILE_VALIDATION_URL }}" \
                VALIDATOR_API_KEY_NAME="${{ env.FILE_VALIDATION_KEY_NAME }}" \
                VALIDATOR_API_KEY_VALUE="${{ env.FILE_VALIDATION_KEY_VALUE }}" \
                VALIDATOR_PARALLEL="${{ env.VALIDATOR_PARALLEL }}" \
                DB_HOST="${{ env.DB_HOST }}" \
                DB_PORT="${{ env.DB_PORT }}" \
                DB_USER="${{ env.DB_USER }}" \
                DB_PASS="${{ env.DB_PASS }}" \
                DB_NAME="${{ env.DB_NAME }}" \
                SOLR_API_URL="${{ env.SOLR_API_URL }}" \
                SOLR_USER="${{ env.SOLR_USER }}" \
                SOLR_PASSWORD="${{ env.SOLR_PASSWORD }}"
